### ISSUE TITLE
Fix Link ....

### ISSUE THREAD

**Issue by 4noxx** [VoronDesign/Voron-Documentation#279]
.... on 
https://docs.vorondesign.com/build/slicer/first_print.html

first link is wrong

**Comment by 4noxx** [comment]
isnt fix
![image](https://user-images.githubusercontent.com/12627059/168481133-cb5dd47d-0abd-4602-8ba5-8af8bf170749.png)

**Comment by bdbell** [comment]
> isnt fix
> 
> ![image](https://user-images.githubusercontent.com/12627059/168481133-cb5dd47d-0abd-4602-8ba5-8af8bf170749.png)
> 
> 

The fix has been submitted but hasn't been pushed live yet. A live push is happening this week.
