### ISSUE TITLE
Z Offset Adjustment Section in https://docs.vorondesign.com/build/startup/

### ISSUE THREAD

**Issue by biggerfish71** [VoronDesign/Voron-Documentation#324]
Klipper has been updated

Z_ENDSTOP_CALIBRATE command now opens a popup screen that gives you buttons to adjust you z offsset instead of using  TESTZ Z=*

**Comment by bythorsthunder** [comment]
This doesn't appear to be a Klipper feature but rather a feature of the UI you are using.  As such unless we confirm that all available UIs have the same functionality no changes to the Docs should be made.  

Klipper still uses the TestZ commands for the Manual Probe Helper Script.
