### ISSUE TITLE
Link to sensorless homing guide is broken on docs.vorondesign.com

### ISSUE THREAD

**Issue by EDGe-17** [VoronDesign/Voron-Documentation#332]
The link is broken to sensorless homing guide in the Voron documentation website. 
Link found on https://docs.vorondesign.com/build/startup/

-Incorrect path https://docs.vorondesign.com/build/startup/Voron-Documentation/blob/main/community/howto/clee/sensorless_xy_homing.md 

-Correct path https://docs.vorondesign.com/community/howto/clee/sensorless_xy_homing.html 

![2023-02-06_16_08_20-Initial_Startup___Voron_Documentation_Mozilla_Firefox](https://user-images.githubusercontent.com/104383985/217157644-1256fa71-b779-422f-bb4f-168013e7c1bc.jpg)

**Comment by timmit99** [comment]
@EDGe-17 both of the links above dont work.

**Comment by timmit99** [comment]
I think you meant to put:

- Correct part https://docs.vorondesign.com/community/howto/clee/sensorless_xy_homing.html

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Documentation/pull/333
