### ISSUE TITLE
Confusing wording in mini12864 instructions

### ISSUE THREAD

**Issue by arkeet** [VoronDesign/Voron-Documentation#47]
https://docs.vorondesign.com/build/electrical/mini12864_klipper_guide.html

A user recently had a problem getting the display working, misunderstanding the header flip image and thinking "yes" meant to flip one connector, and "no" meant to not flip the other. Suggestion:
* Change the words the image to say "correct" and "wrong" or something similar.
* Change step 2 to say something like "Rotate _both_ connector housings 180 degrees and insert back onto pins."

**Comment by gihad** [comment]
I'd suggest also changing the first sentence from `NOTE: The connector housing only` to `NOTE: The 2 connector housings only`

**Comment by bdbell** [comment]
Updated wording in PR #84.
