### ISSUE TITLE
Typo in the Mechanical Assembly page

### ISSUE THREAD

**Issue by royal32** [VoronDesign/Voron-Documentation#58]
I noticed that in the second bullet point on [the Mechanical Assembly page](https://github.com/VoronDesign/Voron-Documentation/blob/main/build/mechanical/index.md#belts), length is spelled lenth.

**Comment by dubjay2k** [comment]
This was addressed with https://github.com/VoronDesign/Voron-Documentation/pull/61.  Issue can be closed.
