### ISSUE TITLE
Add bed ground to Voron v0.0 documentation

### ISSUE THREAD

**Issue by ChaosBlades** [VoronDesign/Voron-Documentation#64]
The Voron v0.0 documentation does not mention adding a ground wire to the AC bed at all. Or is this for some reason not needed?

**Comment by bdbell** [comment]
You are correct there should be a reference to grounding the bed.  However since V0.1 has been released and uses a DC bed this is not longer current.  I have added a stronger note recommending that all AC beds be grounded in the pending PR #84.
