### ISSUE TITLE
Resourcing Guide using s.click.alieexpress.com referrer spam

### ISSUE THREAD

**Issue by ChaosBlades** [VoronDesign/Voron-Documentation#67]
How to block it in Google Analytics:
https://botcrawl.com/block-s-click-alieexpress-com-referrer-spam/

What it is:
https://en.wikipedia.org/wiki/Referrer_spam

**Comment by bdbell** [comment]
Can you please provide an example?

**Comment by ChaosBlades** [comment]
https://s.click.aliexpress.com/e/_dWCqSj2

**Comment by ChaosBlades** [comment]
This is the Google Analytics link on the sourcing guide for the V6. The one I linked above
https://www.google.com/url?q=https://s.click.aliexpress.com/e/_dWCqSj2&sa=D&source=editors&ust=1624995118453000&usg=AOvVaw21Aes6qYrwWhxZXTj9a4t7

There are a couple like this Dragon Hotend that are the correct link to Ali
https://www.google.com/url?q=https://www.aliexpress.com/item/1005002477263672.html?&sa=D&source=editors&ust=1624995118453000&usg=AOvVaw0gCRvuKcsbD3LdXRM1yntm

**Comment by raymondh2** [comment]
s.aliexpress.com denotes affiliate links IIRC. Removing affiliate links isn't really something we want to do completely. But most guides should list both.

**Comment by ChaosBlades** [comment]
I looked it up, it is an affiliate link. I guess ali is doing double duty with these links? 

Seen it was in my DNS blocklist and looked it up. I'll keep it in the block list and just turn my VPN on to bypass when using the Sourcing Guide.
