### ISSUE TITLE
Initial Startup Guide - Problems with setting (0,0)

### ISSUE THREAD

**Issue by conlank** [VoronDesign/Voron-Documentation#83]
Using the instructions on the [Initial startup guide page](https://docs.vorondesign.com/build/startup/) to set (0,0) has some problems. My nozzle is still over the bed at (2.3, 2.6) and using the documentation on the page suggests changing position max in this paragraph:
```
If X and Y offsets are within 5mm or 0,0 is past the bed, the postition_max values should be adjusted to change where the 0,0 point is computed. If the 0,0 is over the bed, the distance from the home point to the front left (position_max) must be increased. If the 0,0 is past the bed, the distance must be decreased. The amount is determined by the output of the M114 command. Update position_max for both [stepper_x] and [stepper_y] as follows:

For X: New = Current - Get Position X (M114) Result
For Y: New = Current - Get Position Y (M114) Result
```

In my case this results in a position_max that is smaller than the endstop_position, leading to klipper throwing an error. This has been suggested to fix by changing both `endstop_position` and `position_max`, which I am testing now.

EDIT: Changing both parameters to the same value allows me to move to 0,0 above the bed without issue. Thank you Timmit for the suggestion!

**Comment by bdbell** [comment]
Text added in PR #84 for clarification.
